### ISSUE TITLE
'domain' is undefined

### ISSUE THREAD

**Issue by piotrpietrzak** [microservice-hackathon/infrastructure#28]
fatal: [localhost] => One or more undefined variables: 'domain' is undefined

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/site.retry

localhost                  : ok=0    changed=0    unreachable=1    failed=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by wybczu** [comment]
Fixed.
